name: Test and Sonarqube Analysis
'on':
  pull_request:

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: gradle test

  sonarqube:
    runs-on: ubuntu-latest
    needs: unittest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Sonarqube analyze
        run: gradle build && gradle sonarqube -Dsonar.projectKey=${{ secrets.SONARQUBE_PROJECT_KEY }} -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }} -Dsonar.branch.name=${GITHUB_REF##*/}