apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: project-templates
  description: A collection of all Organisasi Bawah Tanah project templates
spec:
  type: url
  targets:
    - https://github.com/organisasi-bawah-tanah/backstage-project-templates/blob/main/django/template.yml
    - https://github.com/organisasi-bawah-tanah/backstage-project-templates/blob/main/springboot-jenkins/template.yml
    - https://github.com/organisasi-bawah-tanah/backstage-project-templates/blob/main/springboot/template.yml
