apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{cookiecutter.name | jsonify}}
  description: {{cookiecutter.description | jsonify}}
  annotations:
    github.com/project-slug: {{cookiecutter.destination.owner + "/" + cookiecutter.destination.repo}}
    backstage.io/techdocs-ref: url:{{"https://" + cookiecutter.destination.host + "/" + cookiecutter.destination.owner + "/" + cookiecutter.destination.repo}}
spec:
  type: library
  lifecycle: experimental
  owner: {{cookiecutter.destination.owner | jsonify}}
