apiVersion: v1
kind: Service
metadata:
  name: {{cookiecutter.kubernetes_component_label}}
  labels:
    app: hello
    tier: web
    'backstage.io/kubernetes-id': {{cookiecutter.component_id}}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: {{cookiecutter.http_port}}
  selector:
    app: hello
    tier: web