name: Deploy

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

jobs:
  seria_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2