name: Deploy

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Deploy' 

jobs:
  deploy_terraform:
    runs-on: ubuntu-latest
    steps:


      - uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch   

      - run: |
          echo ${{ steps.extract_branch.outputs.branch }}
          echo GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
