name: Deploy

on: 
  workflow_dispatch:
    inputs:
      tags:
        description: 'Deploy' 

jobs:
  deploy_terraform:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME
          echo GITHUB_ACTOR: $GITHUB_ACTOR
          echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          echo GITHUB_REPOSITORY_OWNER: $GITHUB_REPOSITORY_OWNER
          echo GITHUB_SHA: $GITHUB_SHA
          echo GITHUB_REF: $GITHUB_REF
          echo GITHUB_HEAD_REF: $GITHUB_HEAD_REF
          echo GITHUB_BASE_REF: $GITHUB_BASE_REF
          
      - uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch   


